// <auto-generated />
using System;
using DataAccessLayer.Concrete;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace DataAccessLayer.Migrations
{
    [DbContext(typeof(Context))]
    [Migration("20220101132257_mig1")]
    partial class mig1
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("ProductVersion", "5.0.9")
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("EntityLayer.FiyatTeklif", b =>
                {
                    b.Property<int>("TeklifID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("BurslulukSinavDerecesi")
                        .HasColumnType("int");

                    b.Property<string>("DigerIndirim")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("DigerIndirimMiktari")
                        .HasColumnType("int");

                    b.Property<int>("EkstraIndirimMiktari")
                        .HasColumnType("int");

                    b.Property<string>("EkstraIndirimNedeni")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("ErkenKayitIndirimMiktari")
                        .HasColumnType("int");

                    b.Property<DateTime>("GorusmeTarih")
                        .HasColumnType("datetime2");

                    b.Property<int>("IndirimliKayitUcreti")
                        .HasColumnType("int");

                    b.Property<string>("KayıtAyi")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("KursFiyat")
                        .HasColumnType("int");

                    b.Property<int>("Okulu")
                        .HasColumnType("int");

                    b.Property<int>("SinavOkulIndirimMiktari")
                        .HasColumnType("int");

                    b.Property<int>("ToplamIndirimMiktari")
                        .HasColumnType("int");

                    b.HasKey("TeklifID");

                    b.ToTable("FiyatTeklifs");
                });

            modelBuilder.Entity("EntityLayer.OgrenciBilgi", b =>
                {
                    b.Property<int>("OgrenciID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Adres")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("AnneAdiSoyadi")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("AnneMeslegi")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("AnneTelefonu")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("BabaAdiSoyadi")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("BabaMeslegi")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("BabaTelefonu")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Bolumu")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("DogumTarihi")
                        .HasColumnType("datetime2");

                    b.Property<string>("KayitAlanGorevli")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Notlar")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("OgrenciAdi")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("OgrenciSoyAdi")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Okulu")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("SmsKime")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("TcKimlikNo")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("OgrenciID");

                    b.ToTable("OgrenciBilgies");
                });

            modelBuilder.Entity("EntityLayer.Taksit", b =>
                {
                    b.Property<int>("TaksitID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("OdemeMiktari")
                        .HasColumnType("int");

                    b.Property<DateTime>("OdemeTarihi")
                        .HasColumnType("datetime2");

                    b.Property<int>("TaksitMiktari")
                        .HasColumnType("int");

                    b.Property<int>("TaksitSayisi")
                        .HasColumnType("int");

                    b.Property<DateTime>("TaksitTarihi")
                        .HasColumnType("datetime2");

                    b.Property<int>("ToplamOdenen")
                        .HasColumnType("int");

                    b.HasKey("TaksitID");

                    b.ToTable("Taksits");
                });
#pragma warning restore 612, 618
        }
    }
}
